//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenShop.Catalog.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenShop.Catalog.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialCatalog.
        /// </summary>
        internal static string InitialCatalog {
            get {
                return ResourceManager.GetString("InitialCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreenShop-Catalog.
        /// </summary>
        internal static string MongoCatalog {
            get {
                return ResourceManager.GetString("MongoCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        internal static string MongoConnectionString {
            get {
                return ResourceManager.GetString("MongoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string MongoDatabase {
            get {
                return ResourceManager.GetString("MongoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongo.
        /// </summary>
        internal static string MongoSection {
            get {
                return ResourceManager.GetString("MongoSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqlProduct is null.
        /// </summary>
        internal static string NullSqlProductException {
            get {
                return ResourceManager.GetString("NullSqlProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqlProduct&apos;s and mongoProduct&apos;s MongoId does not match..
        /// </summary>
        internal static string ProductsMismatchException {
            get {
                return ResourceManager.GetString("ProductsMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        internal static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        internal static string SqlSection {
            get {
                return ResourceManager.GetString("SqlSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FailureResponse.
        /// </summary>
        internal static string FailureResponse
        {
            get
            {
                return ResourceManager.GetString("Unable to successfully {0} the {1}: {2}", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product
        {
            get
            {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment
        {
            get
            {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EntityNotFound.
        /// </summary>
        internal static string EntityNotFound
        {
            get
            {
                return ResourceManager.GetString("Specified entity was not presented in the system", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EntityNotFound.
        /// </summary>
        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update
        {
            get
            {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create
        {
            get
            {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
    }
}
